name: Rust Stable

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      # Check code formatting
      - name: Check formatting
        run: cargo fmt --all --check

  build_nightly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux-x86
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binaries
        # run: cargo build --release --target ${{ matrix.target }}
        run: cargo check --all-targets --all-features --release --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --target ${{ matrix.target }}
